name: Deploy Simple
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      APP_DIR: /home/zatint1991-hvt55/zatint1991.com
      BACKEND_DIR: /home/zatint1991-hvt55/zatint1991.com/backend
      FRONTEND_DIR: /home/zatint1991-hvt55/zatint1991.com/frontend
      PUBLIC_DIR: /home/zatint1991-hvt55/zatint1991.com/public/admin-dashboard-2024
      PM2_APP: kintai-api
      PM2_USER: itoshu
      PORT: "8001"
      NODE_ENV: production
      DEPLOY_USER: ${{ secrets.VPS_USER }}
      BUILD_USER: itoshu
      VPS_HOST: ${{ secrets.VPS_HOST }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Add host key
        run: |
          mkdir -p ~/.ssh
          ssh-keygen -R "$VPS_HOST" 2>/dev/null || true
          ssh-keyscan -H "$VPS_HOST" >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Test connection
        run: |
          echo "Testing SSH connection..."
          ssh "$BUILD_USER@$VPS_HOST" "echo 'SSH connection successful'"

      - name: Check VPS status
        run: |
          echo "Checking VPS status..."
          ssh "$BUILD_USER@$VPS_HOST" <<EOF
          echo "VPS Status:"
          echo "Current user: \$(whoami)"
          echo "Current directory: \$(pwd)"
          echo "Disk usage:"
          df -h | head -5
          echo "Memory usage:"
          free -h
          echo "Processes:"
          ps aux | head -10
          EOF
