name: Test Minimal
on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Test basic commands
        run: |
          echo "Testing basic commands..."
          ls -la
          echo "Current directory: $(pwd)"
          echo "Files in root:"
          ls -la | head -10
          
      - name: Test scripts directory
        run: |
          echo "Testing scripts directory..."
          ls -la scripts/ || echo "scripts directory not found"
          if [ -d "scripts" ]; then
            echo "Scripts found:"
            ls -la scripts/ | head -10
          fi
          
      - name: Test script permissions
        run: |
          echo "Testing script permissions..."
          if [ -f "scripts/deploy_rsync.sh" ]; then
            echo "deploy_rsync.sh exists"
            ls -la scripts/deploy_rsync.sh
            chmod +x scripts/deploy_rsync.sh
            echo "Made executable"
            ls -la scripts/deploy_rsync.sh
          else
            echo "deploy_rsync.sh not found"
          fi
          
      - name: Test script execution
        run: |
          echo "Testing script execution..."
          if [ -f "scripts/deploy_rsync.sh" ]; then
            echo "Attempting to run script..."
            bash scripts/deploy_rsync.sh --help || echo "Script failed but that's expected without proper env"
          else
            echo "Script not found, cannot test execution"
          fi
